name: Deploy Frontend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'shared/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"
