name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'shared/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"
